version: "3.8"
services:
  proxy:
    build: proxy
    ports:
    - 443:443
    restart: on-failure
    stop_signal: SIGQUIT
    stop_grace_period: 1s
  target:
    build: target
    ports:
    - 8080:80
    stop_signal: SIGQUIT
    stop_grace_period: 1s
